version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
  kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
      - "9997:9997"
    environment:
      ADVERTISED_HOST: 10.0.138.34
#      ADVERTISED_HOST: 192.168.10.1
      ADVERTISED_PORT: 9092
      JMX_PORT: 9997
    networks:
      - prodnetwork
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - "29000:9000"
    environment:
      ZK_HOSTS: zk:2181
      JMX_PORT: 9997
    networks:
      - prodnetwork
    links:
      - kafka:zk
    depends_on:
      - kafka
